#!/bin/bash
#set -e
##################################################################################################################
# Author 	: Erik Dubois
# Website : https://www.erikdubois.be
# Website	:	https://www.arcolinux.info
# Website	:	https://www.arcolinux.com
# Website	:	https://www.arcolinuxd.com
# Website : https://www.arcolinuxb.com
# Website : https://www.arcolinuxiso.com
# Website	:	https://www.arcolinuxforum.com
##################################################################################################################
#
#   DO NOT JUST RUN THIS. EXAMINE AND JUDGE. RUN AT YOUR OWN RISK.
#
##################################################################################################################

desktop=$DESKTOP_SESSION
case $desktop in
    herbstluftwm )
      herbstclient quit
      ;;
    bspwm )
      pkill bspwm
      ;;
    jwm )
      pkill jwm
      ;;
    openbox )
      pkill openbox
      ;;
    awesome )
      pkill awesome
      ;;
    qtile )
      pkill qtile
	  #qtile-cmd -o cmd -f shutdown
      ;;
    xmonad )
      pkill xmonad
      ;;
    dwm )
      pkill dwm
      ;;
    * )
      echo "#################################"
      echo "You are not supposed to run this"
      echo "#################################"
      ;;
esac
